SELECT YEAR(os.SALES_DATE) AS YEAR, MONTH(os.SALES_DATE) AS MONTH, u.GENDER, COUNT(DISTINCT os.USER_ID) AS TOTAL_MEMBERS
FROM USER_INFO u
JOIN ONLINE_SALE os ON u.USER_ID = os.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), u.GENDER
ORDER BY YEAR(os.SALES_DATE) ASC, MONTH(os.SALES_DATE) ASC, u.GENDER ASC;
